language: node_js
node_js:
  - "4.0.0"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
sudo: false
after_success: npm run report && npm run coveralls
notifications:
  slack:
    secure: WHTtuszxPjFGo8nPpC/qNr5ZG3B4iWeD35i5orXa2E0SYhqEsr8O/jvfQxr4UASytgid4z3vU+qzaat5pLgmIXWapzlpmO8jWxIw+Ps3X2zInsnLve2HmB226tPS6ki5CziW2kKDXadeMIASJ3sm/fbhxgSug4fW7X7H5ziUhGHveXb1wUWPRqQXl20SNsSK1cfVwbQJr3vf/ThvnKI6AuT07ckROryIU5W0lyqdGpYBhHdrlq4rRihYySQX5gKYoBbbcltTly5ayUeHig3w1eo2NHpld3lcEgGxHLgAlL01A3af/a6IjdBxKiCghURGKwnHYUdL8U6vrH/2Sj3t9VdkgtlBurzpV42PXhtL8nTIpYQpGfQGhG8ZfXxEJA3e9lZkWUG54PXCDrLWnRBw/HrSyZoKhuWtdF8WTQuwMin+dzKRtHTbAxwPHCE+mHIk4sFu9nDi3FFHDQYnq3+XrMNk8+085KUE/bf5WToQBJ1yBO3NJKn3IDI2ifsLo02iL2tQeJ46+BN5iPnQcYdiqyto/PeCCuGtf5NuvmoeDvK0BV/lTQ0YBJWuBvd+VUO0DUrTkCC0SG8HlVjhVktqciwyCky8IosXS9TzfncooMq22gRoO/zt4fR19iTojcmZW5fu7LdadBnRHiCX7hEtaPpNMdsyj48a0VkRgM1dzHE=
